blank_issues_enabled: true
contact_links:
  - name: Questions & Discussions
    url: https://github.com/sudouser777/embedded-redis-server/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/sudouser777/embedded-redis-server/blob/main/README.md
    about: Read the full documentation
